"""Initial migration

Revision ID: 997072f64001
Revises:
Create Date: 2025-11-10 17:27:56.473794

"""

# revision identifiers, used by Alembic.
revision = "997072f64001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
